name: avatar_replacement

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image_cropper: ^8.0.2
  image_gallery_saver_plus: ^4.0.1
  flutter_riverpod: ^2.0.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_avatar.png