name: my_local_notifications_demo

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  switcher_button: ^0.0.4
  flutter_easyloading: ^3.0.5

flutter:
  uses-material-design: true