name: show_my_location

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true